module.exports = {
  stakeholderRoute: require('./stakeholder'),
  stakeholdersRoute: require('./stakeholders'),
  organizationRoute: require('./organization'),
  organizationsRoute: require('./organizations'),
  usersRoute: require('./users'),
  themeRoute: require('./theme'),
  themesRoute: require('./themes'),
  indicatorsRoute: require('./indicators'),
  indicatorRoute: require('./indicator'),
  outcomeRoute: require('./outcome'),
  outcomesRoute: require('./outcomes'),
  indicatorReportsRoute: require('./indicatorReports'),
  indicatorReportRoute: require('./indicatorReport'),
  userRoute: require('./user'),
  groupsRoute: require('./groups'),
  groupRoute: require('./group'),
  errorReportRoute: require('./errorReport'),
  fileUploadingRoute: require('./fileUploading'),
  codeRoute: require('./code'),
  codesRoute: require('./codes'),
  characteristicRoute: require('./characteristic'),
  characteristicsRoute: require('./characteristics')
}